name = "portfolio"
main = ".open-next/worker.js"
compatibility_date = "2025-10-31"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[secrets_store_secrets]]
binding = "GITHUB_TOKEN_CF_WORKER"
store_id = "f90683583e754e6e83842e38e2e11faa"
secret_name = "GITHUB_TOKEN"
